services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: ncumt
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: